using Nest;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
    public class Side_effects
    {

        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public Side_effects()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Side_effects(int dIN, string side_effect)
        {
            DIN = dIN;
            Side_effect = side_effect;
        }

        /// <summary>
        /// Clone/Copy constructor.
        /// </summary>
        /// <param name="instance">The object to clone from.</param>
        public Side_effects(Side_effects instance)
            : this(instance.DIN, instance.Side_effect)
        {
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        [JsonProperty(PropertyName = "dIN")]
        public int DIN { get; set; }

        /// <summary>
        /// Name of the doctor.
        /// </summary>
        // [JsonProperty(PropertyName = "name")]
        // public string Name 
        // { get
        //    /* {
        //         return string.Format("{0}", Name);
        //     } */;
        //     set; 
        // }

        /// <summary>
        /// Password of the doctor.
        /// </summary>
        [JsonProperty(PropertyName = "side_effect")]
        public string Side_effect { get; set; }

        /*/// <summary>
        /// FUll name of the student.
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string FullName
        {
            get
            {
                return string.Format("{0} {1}", FirstName, LastName);
            }
        }*/

        #endregion

        #region Methods

        /// <summary>
        /// Overrides the .ToString method.
        /// </summary>
        // public override string ToString()
        // {
        //     return Name;
        // }

        #endregion

    }
}
