using Nest;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace BusinessLibrary.Models
{
    public class WorksAt
    {

        #region Contructors

        /// <summary>
        /// Default constructor. 
        /// Need for serialization purposes.
        /// </summary>
        public WorksAt()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public WorksAt(int medID, int clinicNo)
        {
            MedID = medID;
            ClinicNo = clinicNo;
        }

        /// <summary>
        /// Clone/Copy constructor.
        /// </summary>
        /// <param name="instance">The object to clone from.</param>
        public WorksAt(WorksAt instance)
            : this(instance.MedID, instance.ClinicNo)
        {

        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        [JsonProperty(PropertyName = "medID")]
        public int MedID { get; set; }

        /// <summary>
        /// Name of the doctor.
        /// </summary>
        [JsonProperty(PropertyName = "clinicNo")]
        public int ClinicNo
        {
            get
               /* {
                    return string.Format("{0}", Name);
                } */;
            set;
        }


        #endregion

        #region Methods

        /// <summary>
        /// Overrides the .ToString method.
        /// </summary>
        // public override string ToString()
        // {
        //     return Name;
        // }

        #endregion

    }
}