using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Doctor_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Doctor_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Doctor_db(int id, string name, string password)
        {
            Id = id;
            Name = name;
            Password = password;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>
        public string Password { get; set; }

        #endregion

    }
}
