using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Manufacturer_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Manufacturer_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Manufacturer_db(int manu_id, string name)
        {
            MID = manu_id;
            Name = name;
            // Password = password;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int MID{ get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        public string Name { get; set; }

        // /// <summary>
        // /// Last name used of the student.
        // /// </summary>
        // public string Password { get; set; }

        #endregion

    }
}
