using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Medication_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Medication_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Medication_db(int dIN, bool refillStatus, String expDate, int dosage, int time, int leftoverAmount)
        {
            DIN = dIN;
            RefillStatus = refillStatus;
            ExpDate= expDate;
            Dosage= dosage;
            Time= time;
            LeftoverAmount= leftoverAmount;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int DIN { get; set; }

        /// <summary>
        /// Refill status of medication.
        /// </summary>
        public bool RefillStatus { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>

        public String ExpDate { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>

        public int Dosage { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>

        public int Time { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>

        public int LeftoverAmount { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        #endregion

    }
}
