using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Medication_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Medication_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Medication_db(int DIN, bool RefillStatus, String ExpDate, int Dosage, int Time, int LeftoverAmount)
        {
            DIN = DIN;
            RefillStatus = RefillStatus;
            ExpDate= ExpDate;
            Dosage= Dosage;
            Time= Time;
            LeftoverAmount= LeftoverAmount;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int DIN { get; set; }

        /// <summary>
        /// Refill status of medication.
        /// </summary>
        public bool RefillStatus { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>

        public String ExpDate { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>

        public int Dosage { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>

        public int Time { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>

        public int LeftoverAmount { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        #endregion

    }
}
