using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Patient_db
    {

        #region Contructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Patient_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Patient_db(int healthcareNo, string name, int phoneNo, int doctorId, string password)
        {
            HealthcareNo = healthcareNo;
            Name = name;
            PhoneNo = phoneNo;
            DoctorId = doctorId;
            Password = password;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int HealthcareNo { get; set; }

        /// <summary>
        /// Name of the patient.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Name of the patient.
        /// </summary>
        public int PhoneNo { get; set; }

        /// <summary>
        /// Name of the patient.
        /// </summary>
        public int DoctorId { get; set; }

        /// <summary>
        /// Password of the patient.
        /// </summary>
        public string Password { get; set; }

        #endregion


    }
}