using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Pharmacy_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Pharmacy_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Pharmacy_db(string name, string location, int clinic_no )
        {
            Name= name;
            Location=location;
            ClinicNo= clinic_no;
            // Password = password;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public string Name{ get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        public string Location { get; set; }

        

         /// <summary>
        /// First name used of the student.
        /// </summary>
        public int ClinicNo{ get; set; }

        // /// <summary>
        // /// Last name used of the student.
        // /// </summary>
        // public string Password { get; set; }

        #endregion

    }
}
