using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class Prescription_db
    {

        #region Contructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public Prescription_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public Prescription_db(int healthcareNo, int medDIN, int doctorId, string pharmLocation, string pharmName)
        {
            HealthcareNo = healthcareNo;
            MedDIN = medDIN;
            DoctorId = doctorId;
            PharmLocation = pharmLocation ;
            PharmName = pharmName;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int HealthcareNo { get; set; }

        /// <summary>
        /// Name of the patient.
        /// </summary>
        public int MedDIN { get; set; }


        /// <summary>
        /// Name of the patient.
        /// </summary>
        public int DoctorId { get; set; }

        /// <summary>
        /// Password of the patient.
        /// </summary>
        public string PharmName{ get; set; }

        /// <summary>
        /// Password of the patient.
        /// </summary>
        public string PharmLocation { get; set; }
        #endregion

    }
}