using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class SideEffects_db
    {
        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public SideEffects_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public SideEffects_db(int dIN, String side_effect)
        {
            DIN = dIN;
            Side_effect = side_effect;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int DIN { get; set; }

        /// <summary>
        /// Refill status of medication.
        /// </summary>
        public String Side_effect { get; set; }

        /// <summary>
        /// Last name used of the student.
        /// </summary>

        #endregion

    }
}
