using System;
using System.Collections.Generic;
using System.Text;

namespace DatabaseLibrary.Models
{
    public class WorksAt_db
    {

        #region Constructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        public WorksAt_db()
        {
        }

        /// <summary>
        /// Fields constructor.
        /// </summary>
        public WorksAt_db(int medID, int  clinicNo)
        {
            MedID= medID;
            ClinicNo = clinicNo;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Id generated by our system upon creation of a new instance.
        /// </summary>
        public int ClinicNo { get; set; }

        /// <summary>
        /// First name used of the student.
        /// </summary>
        public int MedID { get; set; }

        #endregion

    }
}
